# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bio-SDRS
version:      0.08
version_from: lib/Bio/SDRS.pm
installdirs:  site
requires:
    Inline:                        0.45
    Math::NumberCruncher:          5.00
    Statistics::Distributions:     1.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
